dist: bionic

jobs:
  include:
    - stage: build docker image
      script:
      - . ./.env
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION -t $DOCKER_IMAGE .
      - docker images
      - docker tag $DOCKER_IMAGE $DOCKER_USERNAME/$DOCKER_IMAGE:$VERSION
      - docker tag $DOCKER_USERNAME/$DOCKER_IMAGE:$VERSION $DOCKER_USERNAME/$DOCKER_IMAGE:latest
      - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$VERSION
    - stage: test
      script: 
      - ./setup.sh
      - . ./.env
      - cd $WORKDIR
      - . $RC
      - ansible --version
